# namespace as mnamespace
apiVersion: v1
kind: Namespace
metadata:
  name: mnamespace
---

# mdeployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdeployment
  namespace: mnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mdeployment
  template:
    metadata:
      labels:
        app: mdeployment
    spec:
      containers:
      - name: whoami-c
        image: traefik/whoami
        ports:
        - containerPort: 80
---

# mservice
apiVersion: v1
kind: Service
metadata:
  name: mservice
  namespace: mnamespace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mdeployment
---

# ndeployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndeployment
  namespace: mnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---

# nservice
apiVersion: v1
kind: Service
metadata:
  name: nservice
  namespace: mnamespace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
