apiVersion: v1
kind: Namespace
metadata:
  name: mnamespace
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdeployment
  namespace: mnamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mdeployment
  template:
    metadata:
      labels:
        app: mdeployment
    spec:
      containers:
      - name: whoami-c
        image: traefik/whoami
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mservice
  namespace: mnamespace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Change this to any port number between 30000-32767
  selector:
    app: mdeployment
